# Phase 1: Data Cleaning and Preprocessing

Objective:
To clean and preprocess the raw exoplanet dataset by handling missing values,
removing duplicates and invalid records, and preparing a clean dataset
for further analysis as described in the preprocessing document.

In [2]:
#STEP 2: Import Libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

print("Libraries imported successfully")

Libraries imported successfully

In [3]:
#STEP 3: Load Raw Dataset
df = pd.read_csv(
    "../data/raw/exoplanet_data.csv",
    comment="#",
    engine="python",
    on_bad_lines="skip"
)

df.shape

(39212, 289)

In [4]:
#View first few rows
df.head()

,rowid,pl_name,hostname,pl_letter,hd_name,hip_name,tic_id,gaia_dr2_id,gaia_dr3_id,default_flag,...,rowupdate,pl_pubdate,releasedate,pl_nnotes,st_nphot,st_nrvc,st_nspec,pl_nespec,pl_ntranspec,pl_ndispec
0,1,11 Com b,11 Com,b,HD 107383,HIP 60202,TIC 72437047,Gaia DR2 3946945413106333696,Gaia DR3 3946945413106333696,1,...,2023-09-19,2023-08,2023-09-19,2.0,1.0,2.0,0.0,0.0,0.0,0.0
1,2,11 Com b,11 Com,b,HD 107383,HIP 60202,TIC 72437047,Gaia DR2 3946945413106333696,Gaia DR3 3946945413106333696,0,...,2014-05-14,2008-01,2014-05-14,2.0,1.0,2.0,0.0,0.0,0.0,0.0
2,3,11 Com b,11 Com,b,HD 107383,HIP 60202,TIC 72437047,Gaia DR2 3946945413106333696,Gaia DR3 3946945413106333696,0,...,2014-07-23,2011-08,2014-07-23,2.0,1.0,2.0,0.0,0.0,0.0,0.0
3,4,11 UMi b,11 UMi,b,HD 136726,HIP 74793,TIC 230061010,Gaia DR2 1696798367260229376,Gaia DR3 1696798367260229376,0,...,2018-04-25,2009-10,2014-05-14,0.0,1.0,1.0,0.0,0.0,0.0,0.0
4,5,11 UMi b,11 UMi,b,HD 136726,HIP 74793,TIC 230061010,Gaia DR2 1696798367260229376,Gaia DR3 1696798367260229376,1,...,2018-09-04,2017-03,2018-09-06,0.0,1.0,1.0,0.0,0.0,0.0,0.0

In [5]:
#Check structure and data types
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 39212 entries, 0 to 39211
Columns: 289 entries, rowid to pl_ndispec
dtypes: float64(254), int64(7), object(28)
memory usage: 86.5+ MB

In [6]:
#Summary statistics
df.describe()

,rowid,default_flag,sy_snum,sy_pnum,sy_mnum,cb_flag,disc_year,rv_flag,pul_flag,ptv_flag,...,sy_kepmag,sy_kepmagerr1,sy_kepmagerr2,pl_nnotes,st_nphot,st_nrvc,st_nspec,pl_nespec,pl_ntranspec,pl_ndispec
count,39212.000000,39212.000000,39212.000000,39212.000000,39212.0,39212.000000,39212.000000,39192.000000,39192.000000,39192.000000,...,31158.000000,0.0,0.0,39162.000000,39162.000000,39162.000000,39162.000000,39162.000000,39162.000000,39162.000000
mean,19606.500000,0.154672,1.085153,1.918622,0.0,0.002397,2015.535346,0.250485,0.000332,0.000051,...,14.112651,NaN,NaN,1.023518,0.470533,0.195879,0.110132,0.108626,0.214443,0.005439
std,11319.673714,0.361596,0.308205,1.238585,0.0,0.048903,4.001613,0.433298,0.018210,0.007143,...,1.439140,NaN,NaN,1.124503,3.796267,0.887284,0.778205,0.931585,1.579140,0.153759
min,1.000000,0.000000,1.000000,1.000000,0.0,0.000000,1992.000000,0.000000,0.000000,0.000000,...,5.973000,NaN,NaN,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,9803.750000,0.000000,1.000000,1.000000,0.0,0.000000,2014.000000,0.000000,0.000000,0.000000,...,13.353000,NaN,NaN,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,19606.500000,0.000000,1.000000,1.000000,0.0,0.000000,2016.000000,0.000000,0.000000,0.000000,...,14.417000,NaN,NaN,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,29409.250000,0.000000,1.000000,2.000000,0.0,0.000000,2016.000000,1.000000,0.000000,0.000000,...,15.212000,NaN,NaN,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,39212.000000,1.000000,4.000000,8.000000,0.0,1.000000,2026.000000,1.000000,1.000000,1.000000,...,17.475000,NaN,NaN,16.000000,70.000000,12.000000,13.000000,19.000000,32.000000,6.000000

In [7]:
#STEP 5: Check Missing Values & Duplicates
df.isnull().sum().sort_values(ascending=False).head(20)

sy_kepmagerr1       39212
sy_kepmagerr2       39212
sy_icmagerr1        39172
sy_icmagerr2        39172
pl_occdeperr1       39168
pl_occdeperr2       39168
sy_icmag            39167
pl_occdeplim        39165
pl_occdep           39165
pl_trueobliqerr1    39152
pl_trueobliqerr2    39152
pl_trueobliq        39147
pl_trueobliqlim     39147
pl_cmassjerr1       39128
pl_cmasseerr2       39128
pl_cmassjerr2       39128
pl_cmasseerr1       39128
pl_cmassj           39124
pl_cmasselim        39124
pl_cmasse           39124
dtype: int64

In [8]:
df.duplicated().sum()

np.int64(0)

In [9]:
#STEP 6: Feature Selection
selected_cols = [
    'pl_name',          # Planet name
    'hostname',         # Star name

    # Planet features
    'pl_rade',          # Planet radius
    'pl_orbper',        # Orbital period
    'pl_orbsmax',       # Semi-major axis
    'pl_eqt',           # Equilibrium temperature

    # Star features
    'st_teff',          # Star temperature
    'st_rad',           # Star radius
    'st_mass',          # Star mass
    'st_met',           # Star metallicity

    # Metadata
    'disc_year',
    'discoverymethod',
    'default_flag'
]

df_clean = df[selected_cols].copy()
df_clean.shape

(39212, 13)

In [10]:
#STEP 6.2: Verify Selected Columns
df_clean.head()

,pl_name,hostname,pl_rade,pl_orbper,pl_orbsmax,pl_eqt,st_teff,st_rad,st_mass,st_met,disc_year,discoverymethod,default_flag
0,11 Com b,11 Com,NaN,323.21000,1.178,NaN,4874.0,13.76,2.09,-0.26,2007,Radial Velocity,1
1,11 Com b,11 Com,NaN,326.03000,1.290,NaN,4742.0,19.00,2.70,-0.35,2007,Radial Velocity,0
2,11 Com b,11 Com,NaN,NaN,1.210,NaN,NaN,NaN,2.60,NaN,2007,Radial Velocity,0
3,11 UMi b,11 UMi,NaN,516.22000,1.540,NaN,4340.0,24.08,1.80,0.04,2009,Radial Velocity,0
4,11 UMi b,11 UMi,NaN,516.21997,1.530,NaN,4213.0,29.79,2.78,-0.02,2009,Radial Velocity,1

In [11]:
df_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 39212 entries, 0 to 39211
Data columns (total 13 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   pl_name          39212 non-null  object
 1   hostname         39212 non-null  object
 2   pl_rade          27015 non-null  float64
 3   pl_orbper        35871 non-null  float64
 4   pl_orbsmax       21936 non-null  float64
 5   pl_eqt           17182 non-null  float64
 6   st_teff          35691 non-null  float64
 7   st_rad           35930 non-null  float64
 8   st_mass          33083 non-null  float64
 9   st_met           24765 non-null  float64
 10  disc_year        39212 non-null  int64
 11  discoverymethod  39212 non-null  object
 12  default_flag     39212 non-null  int64
dtypes: float64(8), int64(2), object(3)
memory usage: 3.9+ MB

In [12]:
#STEP 7: Handling Missing Values
#STEP 7.1: Check Missing Values in df_clean
df_clean.isnull().sum()

pl_name                0
hostname               0
pl_rade            12197
pl_orbper           3341
pl_orbsmax         17276
pl_eqt             22030
st_teff             3521
st_rad              3282
st_mass             6129
st_met             14447
disc_year              0
discoverymethod        0
default_flag           0
dtype: int64

In [13]:
#A) Numeric columns → Median
num_cols = df_clean.select_dtypes(include=['int64', 'float64']).columns
df_clean[num_cols] = df_clean[num_cols].fillna(df_clean[num_cols].median())

In [14]:
#B) Categorical columns → Mode
cat_cols = df_clean.select_dtypes(include=['object']).columns
for col in cat_cols:
    df_clean[col] = df_clean[col].fillna(df_clean[col].mode()[0])

In [15]:
#STEP 7.3: Verify No Missing Values Remain
df_clean.isnull().sum().sum()

np.int64(0)

In [16]:
#STEP 8: Remove Duplicate Rows
#STEP 8.1: Check Duplicate Rows
df_clean.duplicated().sum()

np.int64(5517)

In [17]:
#STEP 8.2: Remove Duplicate
df_clean.drop_duplicates(inplace=True)

In [18]:
#STEP 8.3: Verify Shape After Removing Duplicates
df_clean.shape

(33695, 13)

In [19]:
#STEP 9: Remove Invalid / Physically Impossible Values
#STEP 9.1: Apply Validity Rules
df_clean = df_clean[df_clean['pl_rade'] > 0]      # Planet radius must be positive
df_clean = df_clean[df_clean['pl_orbper'] > 0]   # Orbital period must be positive
df_clean = df_clean[df_clean['pl_eqt'] > 0]      # Temperature must be positive

In [20]:
#STEP 9.2: Check Shape After Validation
df_clean.shape

(33695, 13)

In [21]:
#STEP 10: Final Validation & Save Output
#STEP 10.1: Final Validation (Summary Statistics)
df_clean.describe()

,pl_rade,pl_orbper,pl_orbsmax,pl_eqt,st_teff,st_rad,st_mass,st_met,disc_year,default_flag
count,33695.000000,3.369500e+04,33695.000000,33695.000000,33695.000000,33695.000000,33695.000000,33695.000000,33695.000000,33695.000000
mean,4.078422,1.297497e+04,3.103082,834.568954,5460.164855,1.158131,0.949964,-0.001040,2015.464401,0.179997
std,46.373054,2.191268e+06,146.111180,270.635465,982.119915,1.823855,0.309103,0.164537,4.173406,0.384191
min,0.270000,9.070629e-02,0.004400,34.000000,415.000000,0.012300,0.003100,-2.500000,1992.000000,0.000000
25%,2.022556,4.678064e+00,0.100860,797.000000,5148.000000,0.801000,0.850000,-0.010000,2014.000000,0.000000
50%,2.300000,1.033929e+01,0.100860,797.000000,5613.000000,0.951815,0.959000,-0.003900,2016.000000,0.000000
75%,2.690500,2.323855e+01,0.100860,797.000000,5887.000000,1.200000,1.050000,0.040000,2016.000000,0.000000
max,4282.980000,4.020000e+08,19000.000000,4050.000000,57000.000000,88.475000,23.560000,7.790000,2026.000000,1.000000

In [22]:
df_clean.to_csv("../data/processed/preprocessed.csv", index=False)
print("Phase 1 preprocessing completed successfully.")

Phase 1 preprocessing completed successfully.